# Generated by Django 4.2.5 on 2023-10-09 05:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_alter_avatar_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='avatar',
            name='url_github',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='avatar',
            name='url_linkedin',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
