# Generated by Django 4.2.5 on 2023-10-09 17:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_avatar_url_github_avatar_url_linkedin'),
    ]

    operations = [
        migrations.AddField(
            model_name='avatar',
            name='bio',
            field=models.TextField(max_length=255, null=True),
        ),
    ]
