# Generated by Django 4.2.5 on 2023-10-09 21:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0007_alter_avatar_bio'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='imagen_post',
            field=models.ImageField(blank=True, null=True, upload_to='post'),
        ),
    ]
